/**
 * This file is auto-generated by vite-config/components.ts.
 * Do not edit this file directly.
 */

import type RDFForm from '../components/rdf-form/RDFForm'
import type RDFInput from '../components/rdf-input/RDFInput'

declare global {
  interface HTMLElementTagNameMap {
    'solid-ui-rdf-form': RDFForm
    'solid-ui-rdf-input': RDFInput
  }
}
