import { css, html, LitElement } from 'lit'
import { downArrowIcon } from '../selectShared/downArrow'
import { renderListbox } from '../selectShared/listboxTemplate'
import { SelectOption } from '../selectShared/optionTypes'
import { listboxStyles } from '../selectShared/listboxStyles'
import {
  findOptionIndexByValue,
  getFirstEnabledIndex,
  getLastEnabledIndex,
  getListboxActionFromKey,
  getNextEnabledIndex
} from '../selectShared/keyboard'

/* The following keyboard navigation and ARIA support for Select
  were generated by AI Model: GPT-5.4 */
/* Prompt: can you wire up the keyboard interactions and aria attributes for Select */
export class Select extends LitElement {
  private static _nextId = 0
  private readonly _handleDocumentPointerDown = (event: Event) => {
    const eventTarget = event.target

    if (!this._popupOpen || !(eventTarget instanceof Node)) {
      return
    }

    const eventPath =
      'composedPath' in event
        ? (
            event as Event & { composedPath: () => EventTarget[] }
          ).composedPath()
        : []

    if (eventPath.includes(this)) {
      return
    }

    if (!this.contains(eventTarget)) {
      this._closePopup()
    }
  }

  static properties = {
    label: { type: String, reflect: true },
    theme: { type: String, reflect: true },
    options: { type: Array, reflect: true },
    layout: { type: String, reflect: true },
    value: { type: String, reflect: true },
    _popupOpen: { state: true },
    _activeIndex: { state: true }
  }

  static styles = [
    listboxStyles,
    css`
      :host {
        // default theme
        display: inline-block;
        position: relative;
        z-index: var(--select-z-index, 400);
        box-sizing: border-box;
        --select-open-z-index: 1000;
        --select-popup-z-index: 1001;
        --select-popup-extra-width: 2px;
        --select-popup-background: var(--color-background, #f8f9fb);
        --select-trigger-background: var(--color-background, #f8f9fb);
        --select-trigger-border: 1px solid var(--gray-400, #99a1af);
        --select-trigger-text: var(--color-text-subheading, #101828);
        --select-popup-width: 100%;
        --popup-background: var(--select-popup-background);
        --popup-text: var(--color-text, #1a1a1a);
        --popup-border: var(--color-border, #e5e7eb);
        --popup-shadow: var(
          --box-shadow-sm,
          0 1px 4px rgba(124, 77, 255, 0.12)
        );
      }

      :host([theme='dark']) {
        display: inline-block;
        position: relative;
        z-index: var(--select-z-index, 900);
        box-sizing: border-box;
        --select-open-z-index: 1000;
        --select-popup-z-index: 1001;
        --select-popup-extra-width: 2px;
        --select-popup-background: var(--color-background, #1a1a1a);
        --select-trigger-background: var(--color-background, #1a1a1a);
        --select-trigger-border: 1px solid var(--gray-400, #99a1af);
        --select-trigger-text: var(--color-text-subheading, #f8f9fb);
        --select-popup-width: 100%;
        --popup-background: var(--select-popup-background);
        --popup-text: var(--color-text, #f8f9fb);
        --popup-border: var(--color-border, #e5e7eb);
        --popup-shadow: var(
          --box-shadow-sm,
          0 1px 4px rgba(124, 77, 255, 0.12)
        );
      }

      :host([popup-open]) {
        z-index: var(--select-open-z-index);
      }

      .select-trigger {
        display: flex;
        width: 100%;
        min-height: var(--select-trigger-height, var(--min-touch-target, 44px));
        height: var(--select-trigger-height, var(--min-touch-target, 44px));
        padding: var(--spacing-xxs, 0.3125rem)
          var(--select-trigger-inline-padding, var(--spacing-2xs, 0.625rem));
        align-items: center;
        justify-content: space-between;
        gap: var(--spacing-xxs, 0.3125rem);
        border-radius: var(--border-radius-base, 0.3125rem);
        background: var(--select-trigger-background);
        border: var(
          --select-trigger-border,
          1px solid var(--gray-400, #99a1af)
        );
        color: var(--select-trigger-text);
        cursor: pointer;
        font-family: inherit;
        font-size: var(--font-size-sm, 0.875rem);
        font-weight: var(--font-weight-md, 500);
        line-height: normal;
        text-align: left;
        white-space: nowrap;
        text-decoration: none;
        box-sizing: border-box;
        transition: transform 0.2s ease;
      }

      .select-trigger:active {
        transform: translateY(1px);
      }

      .select-trigger-label {
        flex: 1 1 auto;
        min-width: 0;
        text-align: left;
        overflow: hidden;
        text-overflow: ellipsis;
      }

      .select-trigger-icon {
        display: inline-flex;
        flex: 0 0 auto;
        align-items: center;
        justify-content: center;
        width: 0.75rem;
        height: 0.4375rem;
        pointer-events: none;
      }

      .select-trigger-icon svg {
        width: 100%;
        height: 100%;
        display: block;
      }

      .select-options-section {
        position: relative;
        background: var(--popup-background);
        border-radius: inherit;
        isolation: isolate;
      }

      .popup-box {
        position: absolute;
        top: calc(100% - 1px);
        left: calc(var(--select-popup-extra-width) / -2);
        width: calc(
          var(--select-popup-width) + var(--select-popup-extra-width)
        );
        min-width: calc(
          var(--select-popup-width) + var(--select-popup-extra-width)
        );
        background: var(--popup-background);
        opacity: 1;
        overflow: hidden;
        color: var(--popup-text);
        box-shadow: var(--popup-shadow);
        border: 1px solid var(--popup-border);
        border-radius: var(--border-radius-sm, 0.2rem);
        box-sizing: border-box;
        isolation: isolate;
        z-index: var(--select-popup-z-index);
      }
    `
  ]

  declare label: string
  declare theme: 'light' | 'dark'
  declare options: Array<SelectOption>
  declare layout: 'desktop' | 'mobile'
  declare value: string
  declare _popupOpen: boolean
  declare _activeIndex: number

  private readonly _listboxId = `solid-ui-select-listbox-${Select._nextId++}`

  constructor() {
    super()
    this.label = 'Select an option'
    this.theme = 'light'
    this.layout = 'desktop'
    this.value = ''
    this._popupOpen = false
    this._activeIndex = -1
  }

  connectedCallback() {
    super.connectedCallback()
    document.addEventListener('pointerdown', this._handleDocumentPointerDown)
  }

  disconnectedCallback() {
    document.removeEventListener('pointerdown', this._handleDocumentPointerDown)
    super.disconnectedCallback()
  }

  protected updated() {
    this.toggleAttribute('popup-open', this._popupOpen)
  }

  private _closePopup() {
    this._popupOpen = false
    this._activeIndex = -1
  }

  private _getSelectedIndex() {
    return findOptionIndexByValue(this.options, this.value)
  }

  private _getSelectedOption() {
    const selectedIndex = this._getSelectedIndex()

    if (selectedIndex >= 0) {
      return this.options[selectedIndex]
    }

    return this.options[0]
  }

  private _getDisplayedOptions() {
    const selectedOption = this._getSelectedOption()

    if (!selectedOption) {
      return this.options
    }

    return [
      selectedOption,
      ...this.options.filter((option) => option.value !== selectedOption.value)
    ]
  }

  private _getActiveOption() {
    const popupOptions = this._getDisplayedOptions()

    if (this._activeIndex < 0) {
      return undefined
    }

    return popupOptions[this._activeIndex]
  }

  private _selectValueFromDropdown(uri: string) {
    this.value = uri
    this.dispatchEvent(
      new CustomEvent('change', {
        detail: { value: uri },
        bubbles: true,
        composed: true
      })
    )
    this._closePopup()
  }

  private _selectActiveOption() {
    const activeOption = this._getActiveOption()

    if (activeOption && !activeOption.disabled) {
      this._selectValueFromDropdown(activeOption.value)
    }
  }

  private _openPopup() {
    const popupOptions = this._getDisplayedOptions()

    this._popupOpen = true
    this._activeIndex = findOptionIndexByValue(popupOptions, this.value)

    if (this._activeIndex < 0) {
      this._activeIndex = getFirstEnabledIndex(popupOptions)
    }
  }

  private _handleTriggerKeydown(event: KeyboardEvent) {
    const popupOptions = this._getDisplayedOptions()
    const action = getListboxActionFromKey(event.key)

    if (action === 'none') {
      return
    }

    event.preventDefault()

    switch (action) {
      case 'close':
        this._closePopup()
        break
      case 'first':
        if (!this._popupOpen) {
          this._openPopup()
        }
        this._activeIndex = getFirstEnabledIndex(popupOptions)
        break
      case 'last':
        if (!this._popupOpen) {
          this._openPopup()
        }
        this._activeIndex = getLastEnabledIndex(popupOptions)
        break
      case 'next':
        if (!this._popupOpen) {
          this._openPopup()
          break
        }
        this._activeIndex = getNextEnabledIndex(
          this._activeIndex,
          popupOptions,
          1
        )
        break
      case 'previous':
        if (!this._popupOpen) {
          this._openPopup()
          break
        }
        this._activeIndex = getNextEnabledIndex(
          this._activeIndex,
          popupOptions,
          -1
        )
        break
      case 'select':
        if (!this._popupOpen) {
          this._openPopup()
          break
        }
        this._selectActiveOption()
        break
      default:
        break
    }
  }

  private _getOptionId(option: SelectOption, index: number) {
    return `${this._listboxId}-option-${index}-${option.value}`
  }

  private _renderPopup() {
    const popupOptions = this._getDisplayedOptions()
    const selectedOption = this._getSelectedOption()
    const activeOption = this._getActiveOption()

    return html`
      <div class="popup-box" part="popup-box">
        <div class="select-options-section">
          ${renderListbox({
            selectedOption,
            activeOption,
            options: popupOptions,
            listboxId: this._listboxId,
            getOptionId: (option, index) => this._getOptionId(option, index),
            onOptionSelect: (option) =>
              this._selectValueFromDropdown(option.value)
          })}
        </div>
      </div>
    `
  }

  render() {
    const selectedOption = this._getSelectedOption()
    const activeOption = this._getActiveOption()
    const triggerLabel = selectedOption?.label ?? this.label
    const activeDescendant =
      this._popupOpen && activeOption
        ? this._getOptionId(activeOption, this._activeIndex)
        : undefined

    return html`
      <button
        class="select-trigger"
        type="button"
        aria-haspopup="listbox"
        aria-expanded="${this._popupOpen}"
        aria-controls="${this._listboxId}"
        aria-activedescendant="${activeDescendant ?? ''}"
        part="select-trigger"
        @click="${() => this._openPopup()}"
        @keydown="${this._handleTriggerKeydown}"
      >
        <span class="select-trigger-label" part="trigger-label"
          >${triggerLabel}</span
        >
        <span class="select-trigger-icon" part="trigger-icon" aria-hidden="true"
          >${downArrowIcon}</span
        >
      </button>

      <div
        class="select-root"
        aria-label="Select a value"
        @click="${(e: MouseEvent) => {
          if (e.target === e.currentTarget) this._closePopup()
        }}"
      >
        ${this._popupOpen ? this._renderPopup() : ''}
      </div>
    `
  }
}
